name: Deployment

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    name: Log Deployed
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Log Deployment
        run: echo "Deployed!"